# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/d/stage_wcet/workspace/CMake 2.8/bin/cmake.exe"

# The command to remove a file.
RM = "/d/stage_wcet/workspace/CMake 2.8/bin/cmake.exe" -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = "/d/stage_wcet/workspace/CMake 2.8/bin/cmake-gui.exe"

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /D/stage_wcet/workspace/TC275T-16P

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /D/stage_wcet/workspace/TC275T-16P

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	"/d/stage_wcet/workspace/CMake 2.8/bin/cmake-gui.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/d/stage_wcet/workspace/CMake 2.8/bin/cmake.exe" -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	"/d/stage_wcet/workspace/CMake 2.8/bin/cmake.exe" -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	"/d/stage_wcet/workspace/CMake 2.8/bin/cmake.exe" -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"/d/stage_wcet/workspace/CMake 2.8/bin/cmake.exe" -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /D/stage_wcet/workspace/TC275T-16P/CMakeFiles /D/stage_wcet/workspace/TC275T-16P/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /D/stage_wcet/workspace/TC275T-16P/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named tricore16P

# Build rule for target.
tricore16P: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tricore16P
.PHONY : tricore16P

# fast build rule for target.
tricore16P/fast:
	$(MAKE) -f CMakeFiles/tricore16P.dir/build.make CMakeFiles/tricore16P.dir/build
.PHONY : tricore16P/fast

tricore16P.obj: tricore16P.cpp.obj
.PHONY : tricore16P.obj

# target to build an object file
tricore16P.cpp.obj:
	$(MAKE) -f CMakeFiles/tricore16P.dir/build.make CMakeFiles/tricore16P.dir/tricore16P.cpp.obj
.PHONY : tricore16P.cpp.obj

tricore16P.i: tricore16P.cpp.i
.PHONY : tricore16P.i

# target to preprocess a source file
tricore16P.cpp.i:
	$(MAKE) -f CMakeFiles/tricore16P.dir/build.make CMakeFiles/tricore16P.dir/tricore16P.cpp.i
.PHONY : tricore16P.cpp.i

tricore16P.s: tricore16P.cpp.s
.PHONY : tricore16P.s

# target to generate assembly for a file
tricore16P.cpp.s:
	$(MAKE) -f CMakeFiles/tricore16P.dir/build.make CMakeFiles/tricore16P.dir/tricore16P.cpp.s
.PHONY : tricore16P.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... tricore16P"
	@echo "... tricore16P.obj"
	@echo "... tricore16P.i"
	@echo "... tricore16P.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

